-- 2022년 1월의 도서 판매 데이터를 기준으로
-- AUTHOR_ID, AUTHOR_NAME, CATEGORY, SALES(판매량*판매가)
-- ORDER BY AUTHOR_ID ASC, CATEGORY DESC
WITH JAN_2022_SALES AS(
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES 
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
), BOOK_WITH_SALES AS(
    SELECT b.*, s.SALES
    FROM BOOK b, JAN_2022_SALES s
    WHERE b.BOOK_ID = s.BOOK_ID
)

SELECT 
b.AUTHOR_ID AS AUTHOR_ID, 
a.AUTHOR_NAME AS AUTHOR_NAME, 
b.CATEGORY AS CATEGORY, 
SUM(b.SALES*b.PRICE) AS TOTAL_SALES
FROM BOOK_WITH_SALES b, AUTHOR a
WHERE b.AUTHOR_ID = a.AUTHOR_ID
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC