-- 우유와 요거트를 동시에 구입한 장바쿠니
-- CART_ID ORDER BY CART_ID 

WITH Milk AS(
    SELECT * FROM CART_PRODUCTS WHERE Name = 'Milk'
), Yogurt AS(
    SELECT * FROM CART_PRODUCTS WHERE Name = 'Yogurt'
)

SELECT p.CART_ID
FROM CART_PRODUCTS p 
WHERE EXISTS (SELECT CART_ID FROM Milk WHERE CART_ID = p.CART_ID)
AND EXISTS (SELECT CART_ID FROM Yogurt WHERE CART_ID = p.CART_ID)
GROUP BY p.CART_ID
ORDER BY CART_ID