-- 3세대 대장균의 ID 조회, ORDER BY ID 
WITH RECURSIVE CTE AS(
    SELECT 1 AS GENERATION, ID, PARENT_ID FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT c.GENERATION + 1 AS GENERATION,
    e.ID, e.PARENT_ID
    FROM CTE c, ECOLI_DATA e
    WHERE e.PARENT_ID = c.ID
)

SELECT ID 
FROM CTE
WHERE GENERATION = 3
ORDER BY ID