WITH ECOLI_GENOTYPE AS
(
    SELECT *, 
    MID(CONV(GENOTYPE, 10, 2), -1, 1) AS GENOTYPE1,
    MID(CONV(GENOTYPE, 10, 2), -2, 1) AS GENOTYPE2,
    MID(CONV(GENOTYPE, 10, 2), -3, 1) AS GENOTYPE3,
    MID(CONV(GENOTYPE, 10, 2), -4, 1) AS GENOTYPE4
    FROM ECOLI_DATA
)

SELECT COUNT(*) AS COUNT
FROM ECOLI_GENOTYPE
WHERE (GENOTYPE2 = '' OR GENOTYPE2 = 0)
AND (GENOTYPE1 = 1 OR GENOTYPE3 = 1);