-- 개체의 ID(ID), 자식의 수(CHILD_COUNT)
WITH CHILD_COUNT AS(
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)

SELECT d.ID, 
CASE WHEN c.CHILD_COUNT IS NULL THEN 0
ELSE c.CHILD_COUNT END AS CHILD_COUNT
FROM ECOLI_DATA d
LEFT OUTER JOIN CHILD_COUNT c
ON d.ID = c.PARENT_ID
ORDER BY ID