-- 2022년 3월의 오프라인/온라인 상품 데이터의 판매 날짜, 상품ID, 유저ID, 판매량 조회
-- OFFLINE_SALE 테이블의 판매 데이터의 USER_ID = NULL
-- 판매일 ASC, 상품 ID ASC, 유저 ID ASC

WITH SALE AS (
    SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION ALL
    SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
)

SELECT * 
FROM SALE
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID