-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디(ANIMAL_ID)와 이름(NAME) 조회
-- 보호기간이 긴 순 
WITH DURATION AS(
    SELECT i.*, TIMESTAMPDIFF(MINUTE, i.DATETIME, o.DATETIME) AS MINUTE_DIFF
    FROM ANIMAL_INS i, ANIMAL_OUTS o
    WHERE i.ANIMAL_ID = o.ANIMAL_ID
    ORDER BY MINUTE_DIFF DESC
)


SELECT ANIMAL_ID, NAME
FROM DURATION
LIMIT 2

