WITH AVAILABLE AS(
SELECT 
r.CAR_ID,
MIN(
    CASE WHEN '2022-11-01' <= h.START_DATE AND h.START_DATE <= '2022-11-30' THEN 'N'
         WHEN '2022-11-01' <= h.END_DATE AND h.END_DATE <= '2022-11-30' THEN 'N'
         WHEN h.START_DATE < '2022-11-01'AND '2022-11-30' < h.END_DATE THEN 'N'
    ELSE 'Y' END
) AS AVAILABLE
FROM CAR_RENTAL_COMPANY_CAR r
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON r.CAR_ID = h.CAR_ID
GROUP BY r.CAR_ID
), PRICE AS(
SELECT 
r.CAR_ID, r.CAR_TYPE, FLOOR(r.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) * 0.01) AS FEE   
FROM CAR_RENTAL_COMPANY_CAR r, CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
WHERE r.CAR_TYPE = p.CAR_TYPE
AND p.DURATION_TYPE = '30일 이상'
)

SELECT a.CAR_ID, p.CAR_TYPE, p.FEE 
FROM AVAILABLE a, PRICE p
WHERE a.CAR_ID = p.CAR_ID
AND a.AVAILABLE = 'Y'
AND p.FEE >= 500000 AND p.FEE < 2000000
AND p.CAR_TYPE IN ('세단', 'SUV')
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

# SELECT * FROM CAR_RENTAL_COMPANY_CAR r
# LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
# ON r.CAR_ID = h.CAR_ID WHERE r.CAR_TYPE IN ('세단', 'SUV');