-- 상위 0-25 : CRITICAL, 26-50 - HIGH
-- 51-75: MEDIUM, 76-100: LOW
-- ID, COLONY_NAME ORDER BY ID 
-- MAX(SIZE_RANK) 8일 경우, 상위 25%는 2(8/4)

WITH RANK_ECOLI AS(
    SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
    FROM ECOLI_DATA 
)

SELECT ID,
CASE WHEN SIZE_RANK <= MAX(SIZE_RANK) OVER ()/4 THEN 'CRITICAL'
     WHEN SIZE_RANK <= (MAX(SIZE_RANK) OVER ()/4)*2 THEN 'HIGH'
     WHEN SIZE_RANK <= (MAX(SIZE_RANK) OVER ()/4)*3 THEN 'MEDIUM'
     ELSE 'LOW' END AS 'COLONY_NAME'
FROM RANK_ECOLI
ORDER BY ID