-- ANIMAL_TYPE, NAME, SEX_UPON_INTAKE 
-- ORDER BY ANIAML_ID ASC
-- 이름이 없는 동물의 이름은 "No name"
SELECT 
ANIMAL_TYPE, 
CASE WHEN NAME IS NULL THEN "No name"
ELSE NAME END AS NAME,
SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID