-- 서울에 위치한 REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
-- ROUND(AVG(REVIEW_SCORE), 2) AS SCORE ORDER BY SCORE DESC, FAVORITES DESC
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, 
ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO i, REST_REVIEW r
WHERE i.REST_ID = r.REST_ID
AND i.ADDRESS LIKE '서울%'
GROUP BY i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC