-- 년, 월, 성별 별로 상품을 구매한 회원수 집계
-- YEAR, MONTH, GENDER, USERS(유저수)
-- ORDER BY YEAR, MONTH, GENDER
-- WHERE GENDER IS NOT NULL
SELECT 
YEAR(s.SALES_DATE) AS YEAR,
MONTH(s.SALES_DATE) AS MONTH,
i.GENDER AS GENDER,
COUNT(DISTINCT i.USER_ID) AS USERS
FROM USER_INFO i, ONLINE_SALE s
WHERE i.USER_ID = s.USER_ID
AND i.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER