-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 평균 대여 기간이 7일 이상인 자동차들
-- CAR_ID, 평균대여기간(AVERAGE_DURATION) 
-- ROUND(AVERAGE_DURATION, 1)
-- AVERAGE_DURATION DESC, CAR_ID DESC
SELECT CAR_ID, ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC