WITH USERS AS(
    SELECT USER_ID, JOINED
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' and '2021-12-31'
), USER_SALES AS(
    SELECT * 
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USERS)
    GROUP BY USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)
)

SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, 
(SELECT COUNT(*) FROM USER_SALES WHERE YEAR(SALES_DATE) = YEAR(s.SALES_DATE)
 AND MONTH(SALES_DATE) = MONTH(s.SALES_DATE)) AS PURCHASED_USERS,
ROUND((SELECT COUNT(*) FROM USER_SALES WHERE YEAR(SALES_DATE) = YEAR AND MONTH(SALES_DATE) = MONTH) 
/ (SELECT COUNT(*) FROM USERS), 1) AS PUCHASED_RATIO
FROM USERS u, USER_SALES s
WHERE u.USER_ID = s.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
