-- 각 세대별 자식이 없는 개체의 수 (COUNT)
-- 세대(GENERATION) 조회
-- GENERATION ASC

WITH RECURSIVE CTE (ID, GENERATION, PARENT_ID) AS(
    SELECT ID, 1 AS GENERATION, PARENT_ID
    FROM ECOLI_DATA
    UNION ALL
    SELECT e.ID, c.GENERATION + 1, e.PARENT_ID
    FROM ECOLI_DATA e
    INNER JOIN CTE c
    ON e.PARENT_ID = c.ID
), FINAL AS(
    SELECT ID, MAX(GENERATION) AS GENERATION, MAX(PARENT_ID) AS PARENT_ID
    FROM CTE
    GROUP BY ID
)

SELECT COUNT(*) AS COUNT, GENERATION FROM FINAL f
WHERE (SELECT COUNT(*) FROM FINAL WHERE PARENT_ID = f.ID) = 0
GROUP BY GENERATION
ORDER BY GENERATION