# MAX('대여중', '대여 가능') -> '대여중'

SELECT c.CAR_ID, 	
MAX(CASE WHEN c.START_DATE <= '2022-10-16' AND c.END_DATE >= '2022-10-16' THEN '대여중'
        ELSE '대여 가능' END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
GROUP BY c.CAR_ID
ORDER BY c.CAR_ID DESC;