WITH AMOUNT AS(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT FROM FOOD_ORDER 
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
)

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, 
       p.PRICE * (SELECT TOTAL_AMOUNT FROM AMOUNT WHERE PRODUCT_ID = p.PRODUCT_ID) 
       AS TOTAL_SALES
FROM FOOD_PRODUCT p, AMOUNT a
WHERE p.PRODUCT_ID = a.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC
