-- 7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량 => 큰 순서대로 상위 3개의 맛을 조회
-- FLAVOR
WITH FIRST_TOTAL AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), JULY_TOTAL AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)


SELECT f.FLAVOR
FROM FIRST_TOTAL f
LEFT OUTER JOIN JULY_TOTAL j
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER +
        CASE WHEN j.TOTAL_ORDER IS NOT NULL THEN j.TOTAL_ORDER
        ELSE 0 END) DESC 
LIMIT 3;
