-- 0시부터 23시까지(HOUR), 각 시간대별로 입양이 몇 건(COUNT) 발생했는지 조회
-- 시간대 ASC
WITH RECURSIVE HOURS AS (
    SELECT 0 as n 
    UNION ALL
    SELECT n + 1 FROM HOURS WHERE n < 23
)

# SELECT * FROM HOURS

SELECT n AS HOUR, 
       (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = HOUR) AS COUNT
FROM HOURS