SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM SKILLCODES c, DEVELOPERS d
WHERE c.CATEGORY = 'Front End'
AND c.CODE & d.SKILL_CODE = c.CODE
GROUP BY d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
ORDER BY d.ID;
