-- 96점 이상, S, 20%
-- 90점 이상, A, 15%
-- 80점 이상, B, 10%
-- 이외, C, 0%
-- 사번, 성명, 평가 등급(GRADE), 성과금(BUNUS) 조회
-- EMP_NO ASC

WITH SCORE_AVG AS(
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
),EMP_W_BONUSPCT AS(
    SELECT h.*, 
    CASE WHEN (SELECT SCORE FROM SCORE_AVG WHERE EMP_NO = h.EMP_NO) >= 96 THEN 'S'
         WHEN (SELECT SCORE FROM SCORE_AVG WHERE EMP_NO = h.EMP_NO)  >= 90 THEN 'A'
         WHEN (SELECT SCORE FROM SCORE_AVG WHERE EMP_NO = h.EMP_NO)  >= 80 THEN 'B'
         ELSE 'C' END AS GRADE,
    CASE WHEN (SELECT SCORE FROM SCORE_AVG WHERE EMP_NO = h.EMP_NO)  >= 96 THEN 0.2
         WHEN (SELECT SCORE FROM SCORE_AVG WHERE EMP_NO = h.EMP_NO)  >= 90 THEN 0.15
         WHEN (SELECT SCORE FROM SCORE_AVG WHERE EMP_NO = h.EMP_NO)  >= 80 THEN 0.1
         ELSE 0 END AS BONUS_PCT
    FROM HR_EMPLOYEES h
)

SELECT EMP_NO, EMP_NAME, GRADE, SAL * BONUS_PCT AS BONUS
FROM EMP_W_BONUSPCT
ORDER BY EMP_NO