-- MEMBER_PROFILE 와 REST_REVIEW 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
-- REVIEW_DATE, REVIEW_TEXT
# WITH MEMBER_REVIEW_CNT AS(
#     SELECT MEMBER_ID, COUNT(*)

# )

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVEIW_DATE
FROM REST_REVIEW r, MEMBER_PROFILE m
WHERE r.MEMBER_ID = m.MEMBER_ID
AND r.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT