-- 편차(YEAR_DEV) : 분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기
-- 연도에 대해 오름차순으로 정렬
-- 같은 연도에 대해서는 대장균 크기의 편차에 대해 오름차순 정렬

WITH ECOLI_MAX AS 
(
    SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT m.YEAR, m.MAX_SIZE - d.SIZE_OF_COLONY AS YEAR_DEV, d.ID
FROM ECOLI_DATA d, ECOLI_MAX m
WHERE YEAR(d.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY m.YEAR, YEAR_DEV;