WITH MAX_LENG AS(
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENG
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT i.ID AS ID, n.FISH_NAME AS FISH_NAME, i.LENGTH AS LENGTH
FROM FISH_INFO i, FISH_NAME_INFO n
WHERE i.FISH_TYPE = n.FISH_TYPE
AND i.LENGTH = (SELECT MAX_LENG FROM MAX_LENG WHERE FISH_TYPE = n.FISH_TYPE)
ORDER BY ID;