-- AVG(LENGTH) >= 33 종류별로 분류
-- 잡은 수(FISH_COUNT), 최대 길이(MAX_LENGTH), 물고기의 종류(FISH_TYPE) 조회
-- ORDER BY FISH_TYPE 
-- 10cm 이하의 물고기들은 10cm 로 취급
WITH NEW_FISH_INFO AS(
    SELECT ID, FISH_TYPE, 
    CASE WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH END AS LENGTH
    FROM FISH_INFO
), AVG_LENGTH_33 AS(
    SELECT FISH_TYPE, AVG(LENGTH) AS AVG_LENGTH
    FROM NEW_FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG_LENGTH >= 33
)

SELECT COUNT(LENGTH) AS FISH_COUNT, 
MAX(LENGTH) AS MAX_LENGTH,
FISH_TYPE 
FROM NEW_FISH_INFO i
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM AVG_LENGTH_33)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE

    
